/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrTable: typeof import('@gouvminint/vue-dsfr')['DsfrTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
